"""add odds line column

Revision ID: 6b88b1e471a7
Revises: e69c03c531bd
Create Date: 2026-09-12 13:05:21.143858

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b88b1e471a7'
down_revision: str | None = 'e69c03c531bd'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match_odds', sa.Column('line', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match_odds', 'line')
    # ### end Alembic commands ###
