"""initial schema

Revision ID: e69c03c531bd
Revises: 
Create Date: 2026-09-12 12:57:00.030646

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e69c03c531bd'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('RUNNING', 'SUCCESS', 'FAILED', name='ingestionstatus', native_enum=False), nullable=False),
    sa.Column('rows_ingested', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_runs_source'), 'ingestion_runs', ['source'], unique=False)
    op.create_table('leagues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leagues_code'), 'leagues', ['code'], unique=True)
    op.create_table('seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=16), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_name'), 'teams', ['name'], unique=True)
    op.create_table('elo_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('elo', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_elo_ratings_date'), 'elo_ratings', ['date'], unique=False)
    op.create_index(op.f('ix_elo_ratings_team_id'), 'elo_ratings', ['team_id'], unique=False)
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('home_goals', sa.Integer(), nullable=True),
    sa.Column('away_goals', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('HISTORICAL', 'SCHEDULED', name='matchstatus', native_enum=False), nullable=False),
    sa.Column('source_ids', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_away_team_id'), 'matches', ['away_team_id'], unique=False)
    op.create_index(op.f('ix_matches_date'), 'matches', ['date'], unique=False)
    op.create_index(op.f('ix_matches_home_team_id'), 'matches', ['home_team_id'], unique=False)
    op.create_index(op.f('ix_matches_league_id'), 'matches', ['league_id'], unique=False)
    op.create_index(op.f('ix_matches_season_id'), 'matches', ['season_id'], unique=False)
    op.create_index(op.f('ix_matches_status'), 'matches', ['status'], unique=False)
    op.create_table('match_odds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('bookmaker', sa.String(length=64), nullable=False),
    sa.Column('market', sa.String(length=32), nullable=False),
    sa.Column('selection', sa.String(length=32), nullable=False),
    sa.Column('odds', sa.Float(), nullable=False),
    sa.Column('snapshot_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_odds_market'), 'match_odds', ['market'], unique=False)
    op.create_index(op.f('ix_match_odds_match_id'), 'match_odds', ['match_id'], unique=False)
    op.create_index(op.f('ix_match_odds_snapshot_time'), 'match_odds', ['snapshot_time'], unique=False)
    op.create_table('model_predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.Column('market', sa.String(length=32), nullable=False),
    sa.Column('selection', sa.String(length=32), nullable=False),
    sa.Column('prob_market_implied', sa.Float(), nullable=False),
    sa.Column('prob_model', sa.Float(), nullable=False),
    sa.Column('ev', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='risklevel', native_enum=False), nullable=False),
    sa.Column('is_recommended', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_predictions_ev'), 'model_predictions', ['ev'], unique=False)
    op.create_index(op.f('ix_model_predictions_is_recommended'), 'model_predictions', ['is_recommended'], unique=False)
    op.create_index(op.f('ix_model_predictions_market'), 'model_predictions', ['market'], unique=False)
    op.create_index(op.f('ix_model_predictions_match_id'), 'model_predictions', ['match_id'], unique=False)
    op.create_table('team_match_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('xg', sa.Float(), nullable=True),
    sa.Column('xga', sa.Float(), nullable=True),
    sa.Column('shots', sa.Integer(), nullable=True),
    sa.Column('shots_on_target', sa.Integer(), nullable=True),
    sa.Column('possession', sa.Float(), nullable=True),
    sa.Column('elo_pre', sa.Float(), nullable=True),
    sa.Column('elo_post', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_match_stats_match_id'), 'team_match_stats', ['match_id'], unique=False)
    op.create_index(op.f('ix_team_match_stats_team_id'), 'team_match_stats', ['team_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_match_stats_team_id'), table_name='team_match_stats')
    op.drop_index(op.f('ix_team_match_stats_match_id'), table_name='team_match_stats')
    op.drop_table('team_match_stats')
    op.drop_index(op.f('ix_model_predictions_match_id'), table_name='model_predictions')
    op.drop_index(op.f('ix_model_predictions_market'), table_name='model_predictions')
    op.drop_index(op.f('ix_model_predictions_is_recommended'), table_name='model_predictions')
    op.drop_index(op.f('ix_model_predictions_ev'), table_name='model_predictions')
    op.drop_table('model_predictions')
    op.drop_index(op.f('ix_match_odds_snapshot_time'), table_name='match_odds')
    op.drop_index(op.f('ix_match_odds_match_id'), table_name='match_odds')
    op.drop_index(op.f('ix_match_odds_market'), table_name='match_odds')
    op.drop_table('match_odds')
    op.drop_index(op.f('ix_matches_status'), table_name='matches')
    op.drop_index(op.f('ix_matches_season_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_league_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_home_team_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_date'), table_name='matches')
    op.drop_index(op.f('ix_matches_away_team_id'), table_name='matches')
    op.drop_table('matches')
    op.drop_index(op.f('ix_elo_ratings_team_id'), table_name='elo_ratings')
    op.drop_index(op.f('ix_elo_ratings_date'), table_name='elo_ratings')
    op.drop_table('elo_ratings')
    op.drop_index(op.f('ix_teams_name'), table_name='teams')
    op.drop_table('teams')
    op.drop_table('seasons')
    op.drop_index(op.f('ix_leagues_code'), table_name='leagues')
    op.drop_table('leagues')
    op.drop_index(op.f('ix_ingestion_runs_source'), table_name='ingestion_runs')
    op.drop_table('ingestion_runs')
    # ### end Alembic commands ###
